export const SAVE_PRODUCT_REQUEST = "SAVE_PRODUCT_REQUEST";
export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
