server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  mvc:
    dispatch-options-request: true

jwt:
  secret-key: imarket
